import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { ArrowLeft, Save, KeyRound, Copy, Check } from 'lucide-react';
import PageHeader from '../../../components/PageHeader';
import FormField from '../../../components/FormField';
import { getContact, createContact, updateContact } from '../../../api/contacts';
import toast from 'react-hot-toast';

const TYPE_OPTS = [
  { value: 'customer', label: 'Customer' },
  { value: 'vendor',   label: 'Vendor'   },
  { value: 'both',     label: 'Both'     },
];

export default function ContactForm() {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEdit = !!id;
  const [loading, setLoading] = useState(false);
  const [fetching, setFetching] = useState(isEdit);
  const [copied, setCopied] = useState(false);
  const { register, handleSubmit, watch, reset, formState: { errors } } = useForm({
    defaultValues: {
      type: 'customer',
    },
  });

  const emailVal = watch('email', '');

  useEffect(() => {
    if (!isEdit) return;
    getContact(id)
      .then(r => { reset(r.data.data); setFetching(false); })
      .catch(() => { toast.error('Contact not found.'); navigate('/contacts'); });
  }, [id, reset, navigate, isEdit]);

  const copyCredentials = () => {
    const text = `Urban Furniture Customer Portal:\nLogin URL: ${window.location.origin}/login\nLogin ID: ${emailVal}\nPassword: portal123`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success('Customer portal credentials copied to clipboard!');
    setTimeout(() => setCopied(false), 2500);
  };

  const onSubmit = async (values) => {
    setLoading(true);
    try {
      if (isEdit) {
        await updateContact(id, values);
        toast.success('Contact updated!');
      } else {
        await createContact(values);
        toast.success('Contact created! Customer portal login generated.');
      }
      navigate('/contacts');
    } catch (err) {
      toast.error(err.response?.data?.error?.message ?? 'Save failed.');
    } finally {
      setLoading(false);
    }
  };

  if (fetching) return <div className="flex items-center justify-center h-48 text-gray-400">Loading...</div>;

  return (
    <div>
      <PageHeader title={isEdit ? 'Edit Contact' : 'New Contact'} subtitle="Customers and vendors">
        <button className="btn-secondary" onClick={() => navigate('/contacts')}><ArrowLeft size={15} /> Back</button>
        <button className="btn-primary" form="contact-form" type="submit" disabled={loading} id="save-contact-btn">
          <Save size={15} /> {loading ? 'Saving...' : 'Save'}
        </button>
      </PageHeader>

      <div className="card p-6 max-w-2xl">
        {/* Customer Portal Credentials Info Box for the Accountant */}
        {emailVal && (
          <div className="mb-6 p-4 rounded-xl bg-indigo-50/80 dark:bg-indigo-950/30 border border-indigo-200 dark:border-indigo-800/60">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-indigo-900 dark:text-indigo-200 font-medium text-sm">
                <KeyRound size={16} className="text-indigo-600 dark:text-indigo-400" />
                Customer Portal Login (Generated by Accountant)
              </div>
              <button
                type="button"
                onClick={copyCredentials}
                className="inline-flex items-center gap-1.5 px-2.5 py-1 text-xs font-medium text-indigo-700 dark:text-indigo-300 bg-white dark:bg-indigo-900/60 rounded-md border border-indigo-200 dark:border-indigo-700 hover:bg-indigo-50 dark:hover:bg-indigo-900 transition-colors"
              >
                {copied ? <Check size={13} className="text-emerald-500" /> : <Copy size={13} />}
                {copied ? 'Copied' : 'Copy Credentials'}
              </button>
            </div>
            <div className="mt-2 text-xs text-indigo-700 dark:text-indigo-300 grid grid-cols-1 sm:grid-cols-2 gap-2">
              <div>
                <span className="text-gray-500 dark:text-gray-400">Customer Login ID:</span>{' '}
                <code className="font-mono bg-white/70 dark:bg-black/30 px-1.5 py-0.5 rounded">{emailVal}</code>
              </div>
              <div>
                <span className="text-gray-500 dark:text-gray-400">Default Password:</span>{' '}
                <code className="font-mono bg-white/70 dark:bg-black/30 px-1.5 py-0.5 rounded">portal123</code>
              </div>
            </div>
            <p className="mt-2 text-[11px] text-indigo-600/80 dark:text-indigo-400/80">
              Customers do not register online. Provide these credentials to the customer to access invoices and payments on the login page.
            </p>
          </div>
        )}

        <form id="contact-form" onSubmit={handleSubmit(onSubmit)} className="grid grid-cols-1 sm:grid-cols-2 gap-4" noValidate>
          <div className="sm:col-span-2">
            <FormField label="Contact Name" name="name" required register={register} error={errors.name}
              placeholder="e.g. Rahul Sharma"
              {...register('name', { required: 'Name is required' })}
            />
          </div>
          <FormField label="Type" name="type" type="select" register={register} options={TYPE_OPTS} error={errors.type}
            {...register('type', { required: 'Type is required' })}
          />
          <FormField label="Email (Used as Portal Login ID)" name="email" type="email" register={register} error={errors.email} placeholder="email@example.com"
            {...register('email')}
          />
          <FormField label="Mobile" name="mobile" register={register} placeholder="+91 9XXXXXXXXX" {...register('mobile')} />
          <FormField label="City" name="city" register={register} {...register('city')} />
          <FormField label="State" name="state" register={register} {...register('state')} />
          <FormField label="Pincode" name="pincode" register={register} {...register('pincode')} />
          <div className="sm:col-span-2">
            <FormField label="Street / Address" name="street" type="textarea" register={register} {...register('street')} />
          </div>
          <div className="sm:col-span-2">
            <FormField label="Image URL" name="image_url" register={register} placeholder="https://..." {...register('image_url')} />
          </div>
        </form>
      </div>
    </div>
  );
}
